format = """
[]({color1})\
$os\
$username\
[](bg:{color2} fg:{color1})\
$directory\
[](fg:{color2} bg:{color3})\
$git_branch\
$git_status\
[](fg:{color3} bg:{color4})\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:{color4} bg:{color5})\
$docker_context\
[](fg:{color5} bg:{color15})\
$time\
[ ](fg:{color15})\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:{color1}"
style_root = "bg:{color1}"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:{color1}"
disabled = true # Disabled by default

[directory]
style = "bg:{color2}"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:{color4}"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:{color5}"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:{color4}"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:{color4} fg:{color0}"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:{color3} fg:{color0}"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:{color3} fg:{color0}"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:{color4} fg:{color0}"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:{color4} fg:{color0}"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:{color4} fg:{color0}"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:{color4} fg:{color0}"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:{color4} fg:{color0}"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:{color4} fg:{color0}"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:{color4} fg:{color0}"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:{color4} fg:{color0}"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:{color4} fg:{color0}"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:{color15} fg:{color0}"
format = '[  $time ]($style)'
